name: Release Go Module

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build and publish
        run: |
          go mod tidy
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v1.0.0 -m "Release v1.0.0"
          git push origin v1.0.0
